# COPIA UNA IMAGEN DESDE DOCKER HUB LLAMADA NODE 14
FROM node:14

# VAMOS A TRABAJAR EN UNA CARPETA LLAMADA /usr/src DENTRO DEL CONTENEDOR
WORKDIR /usr/src

# SE COPIA EL PACKAGE.JSON A LA RAIZ DE LA APLICACION
COPY package.json ./

# SE COPIA EL YARN.LOCK A LA RAIZ DE LA APLICACION
COPY yarn.lock ./

# COPIAMOS AL RESTO DE ARCHIVOS 
COPY ./ ./

# INSTALACION DE LAS LIBRERIAS
RUN yarn install

# EJECUCION
CMD ["yarn", "start"]